directories:
  base_dir: .
  data:
    path: data
    experimental: experimental
      path: experimental
    analysis: analysis
      path: analysis
  extractions:
    path: extractions
    models:
      path: models
      kinematic_sets: kinematic_sets